In [1]:
# load libraries and set plot parameters
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

from IPython.display import set_matplotlib_formats
set_matplotlib_formats('pdf', 'png')
plt.rcParams['savefig.dpi'] = 75
plt.rcParams['figure.autolayout'] = False
#plt.rcParams['figure.figsize'] = 10, 6
plt.rcParams['figure.figsize'] = 14, 8
plt.rcParams['axes.labelsize'] = 18
plt.rcParams['axes.titlesize'] = 20
plt.rcParams['font.size'] = 16
plt.rcParams['lines.linewidth'] = 2.0
plt.rcParams['lines.markersize'] = 8
plt.rcParams['legend.fontsize'] = 22
plt.rcParams['text.usetex'] = True
plt.rcParams['font.family'] = "serif"
plt.rcParams['font.serif'] = "cm"

import scipy.constants as cte
from scipy.integrate import simps
from scipy.signal import gaussian

from core.evolution import imaginary
from core.empirical import in_segregation

au_l   = cte.value('atomic unit of length')
au_t   = cte.value('atomic unit of time')
au_e   = cte.value('atomic unit of energy')
ev     = cte.value('electron volt')
au2ang = au_l / 1e-10
au2ev  = au_e / ev

In [21]:
valores_x0 = {}
for x0 in [3.25, 3.5, 3.75, 4.0]:
    # otimizando
    L = (x0 * au2ang) * 2 # angstron
    N = 1024
    hN = int(N/2)
    dt = 5e-18 # s

    # unidades atomicas
    L_au = L / au2ang
    dt_au = -1j * dt / au_t

    # malhas direta e reciproca
    x_au = np.linspace(-L_au/2.0, L_au/2.0, N)

    # props do material
    me_eff = 0.5
    adw_k0 = 0.0#-132.7074997
    k2 = 7.0
    k3 = 0.5
    k4 = 1.0
    v_adw = lambda x: adw_k0-k2*x**2+k3*x**3+k4*x**4
    v_au = np.vectorize(v_adw)(x_au)

    valores = imaginary(x_au,v_au ,  me_eff, nmax=9, precision=1e-6)
    valores_x0[x0] = valores

In [24]:
valores_x0[3.5]['eigenvalues']

array([-12.25841771,  -6.04546034,  -5.28580938,  -0.64612098,
         0.69161994,   4.05531264,   7.3694291 ,  11.24640821,  15.43169607])

In [27]:
valores_x0[4.0]['eigenvalues']*au2ev

array([-333.56984504, -164.5057382 , -143.84273048,  -17.59156313,
         18.80960582,  110.29311578,  200.5169851 ,  305.72800421,
        419.91168633])

In [9]:
np.array([-12.258438, -6.045418, -5.286089, -0.646627, 0.691204, 4.053229, 7.368937, 11.235521, 15.431918])*au2ev

array([-333.56908841, -164.50420285, -143.84180831,  -17.59561691,
         18.80861886,  110.29397894,  200.51898926,  305.73409906,
        419.92387772])

In [10]:
valores_x0[3.75]['eigenvalues']*au2ev

array([-333.56965376, -164.50559808, -143.84193125,  -17.59094976,
         18.81098088,  110.29577762,  200.5203479 ,  305.73889799,
        419.91914044])

In [15]:
np.array([-12.258805, -6.045688, -5.286878, -0.646579, 0.690373, 4.052328, 7.367605, 11.233792, 15.429527])*au2ev

array([-333.57907499, -164.51154992, -143.8632781 ,  -17.59431076,
         18.7860062 ,  110.26946149,  200.48274369,  305.68705057,
        419.8588153 ])

In [16]:
print(au2ev*np.array([-12.258992, -6.045790, -5.289386, -0.652531, 0.666824, 4.009543, 7.241761, 10.819522, 14.581101]))
print(au2ev*np.array([-12.258824, -6.045688, -5.287076, -0.647054, 0.689775, 4.051291, 7.364894, 11.227179, 15.413241]))
print(au2ev*np.array([-12.258805, -6.045688, -5.286878, -0.646579, 0.690373, 4.052328, 7.367605, 11.233792, 15.429527]))
print(au2ev*np.array([-12.258799, -6.045687, -5.286859, -0.646541, 0.690390, 4.052355, 7.367668, 11.233904, 15.429861]))


[-333.58416352 -164.51432548 -143.93152425  -17.75627293   18.14520527
  109.10522233  197.05835403  294.41418969  396.7719679 ]
[-333.57959201 -164.51154992 -143.86866595  -17.60723617   18.76973379
  110.24124328  200.40897363  305.50710168  419.41565066]
[-333.57907499 -164.51154992 -143.8632781   -17.59431076   18.7860062
  110.26946149  200.48274369  305.68705057  419.8588153 ]
[-333.57891172 -164.51152271 -143.86276108  -17.59327673   18.78646879
  110.27019619  200.48445801  305.69009825  419.8679039 ]
